### PR TITLE
Use Tyrian theme for UI

### PR DESCRIPTION
**Pull request by oxr463**
See: https://gitlab.com/oxr463/buildbot_tyrian_theme

### CODE REVIEW

**Comment by mjeveritt** [comment]
Interesting!

I can't seem to install on my testing instance. Despite installing, I'm getting a 'cannot find tyrian_view plugin' error from buildbot.
Of course, it's entirely possible that my instance is far too old to work properly with this feature, but still ... :joy:
Version info at https://kernel-ci.emjay-embedded.co.uk

**Comment by mjeveritt** [comment]
FYI, doesn't look like the travis build failure relates specifically to this PR, but I'll dig deeper later.

**Comment by aliceinwire** [comment]
@mjeveritt I think you need to enable it in the buildbot plugins

**Comment by mjeveritt** [comment]
> @mjeveritt I think you need to enable it in the buildbot plugins
> from your plugin list is not enabled

I was being an idiot, and using 'buildbot reconfig' and not 'buildbot restart' .. and hence it couldn't *find* the non-existant plugin to reconfigure ... derp. :slightly_frowning_face: 
"As you were ..."

Thanks for the tip, @aliceinwire, that prompted me to probe deeper!

**Comment by oxr463** [comment]
I apologize, it apears I overlooked that part. The instructions to install the plugin are here, <https://gitlab.com/oxr463/buildbot_tyrian_theme#installation>. I should fix that in my PR.

**Comment by oxr463** [comment]
Depends on: https://gitlab.com/oxr463/buildbot_tyrian_theme/issues/3

**Comment by aliceinwire** [comment]
looks nice really nice :+1:

**Comment by aliceinwire** [comment]
dosen't work with docker buildbot master.

```
buildbot_1  | 2019-12-01 15:39:07+0000 [-] while starting BuildMaster
buildbot_1  |   Traceback (most recent call last):
buildbot_1  |     File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
buildbot_1  |       result = g.send(result)
buildbot_1  |     File "/usr/lib/python3.6/site-packages/buildbot/util/service.py", line 49, in reconfigServiceWithBuildbotConfig
buildbot_1  |       yield svc.reconfigServiceWithBuildbotConfig(new_config)
buildbot_1  |     File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
buildbot_1  |       return _cancellableInlineCallbacks(gen)
buildbot_1  |     File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
buildbot_1  |       _inlineCallbacks(None, g, status)
buildbot_1  |   --- <exception caught here> ---
buildbot_1  |     File "/usr/lib/python3.6/site-packages/buildbot/master.py", line 296, in startService
buildbot_1  |       yield self.reconfigServiceWithBuildbotConfig(self.config)
buildbot_1  |     File "/usr/lib/python3.6/site-packages/buildbot/util/service.py", line 49, in reconfigServiceWithBuildbotConfig
buildbot_1  |       yield svc.reconfigServiceWithBuildbotConfig(new_config)
buildbot_1  |     File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
buildbot_1  |       result = g.send(result)
buildbot_1  |     File "/usr/lib/python3.6/site-packages/buildbot/www/service.py", line 209, in reconfigServiceWithBuildbotConfig
buildbot_1  |       self.setupSite(new_config)
buildbot_1  |     File "/usr/lib/python3.6/site-packages/buildbot/www/service.py", line 283, in setupSite
buildbot_1  |       self.configPlugins(root, new_config)
buildbot_1  |     File "/usr/lib/python3.6/site-packages/buildbot/www/service.py", line 264, in configPlugins
buildbot_1  |       "could not find plugin %s; is it installed?" % (key,))
buildbot_1  |   builtins.RuntimeError: could not find plugin tyrian_view; is it installed?
```

**Comment by aliceinwire** [comment]
can you please rebase ?

**Comment by oxr463** [comment]
> 
> 
> Please rebase

Done.

**Pull request merged**
