### PR TITLE
Change port for Web Interface

### PR DESCRIPTION
**Pull request by oxr463**

### CODE REVIEW

**Comment by aliceinwire** [comment]
I would prefer to deal with ssl instead of using port 80

something like this
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion

**Comment by mjeveritt** [comment]
I'm using a reverse-proxy on kernel-ci.emjay-embedded.co.uk, and it works quite well :)

**Comment by aliceinwire** [comment]
```
  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```

**Comment by aliceinwire** [comment]
fixed by https://github.com/aliceinwire/GkernelCI_docker

**Comment by oxr463** [comment]
> Warning: c['buildbotURL'] is misconfigured to

> https://kernel1.amd64.dev.gentoo.org

> Should be:

> https://kernel1.amd64.dev.gentoo.org/

**Comment by oxr463** [comment]
Also the link on the [Wiki Page](https://wiki.gentoo.org/wiki/GKernelCI) should be updated also.

> # URL
>
> http://kernel1.amd64.dev.gentoo.org:8010
>
> if you want a user account please ask to Alicef 

Should be https://kernel1.amd64.dev.gentoo.org

**Pull request closed without merging**
